services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    command:
      - '--path.rootfs=/host'
      - '--web.disable-exporter-metrics'
      - '--collector.disable-defaults'
      - '--collector.mdadm'
      - '--collector.filesystem'
      - '--collector.diskstats'
      - '--collector.cpu'
      - '--collector.cpufreq'
      - '--collector.ethtool'
      - '--collector.netdev'
      - '--collector.netstat'
      - '--collector.meminfo'
      - '--collector.hwmon'
      - '--collector.uname'
      - '--collector.time'
      - '--collector.stat'
      - '--collector.filesystem.fs-types-include=(ext4)'
    pid: host
    user: root
    hostname: nugget_node
    ports:
      - "9100:9100"
    volumes:
      - '/:/host:ro'

  smartctl-exporter:
    image: prometheuscommunity/smartctl-exporter
    privileged: true
    user: root
    ports:
      - "9633:9633"
    volumes:
      - ./drivedb.h.new:/usr/share/smartmontools/drivedb.h
    command:
      - "--smartctl.device=/dev/sda"
      - "--smartctl.device=/dev/sdb"
      - "--smartctl.device=/dev/sdc"
      - "--smartctl.powermode-check=never"

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
