services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--web.disable-exporter-metrics'
      - '--collector.disable-defaults'
      - '--collector.mdadm'
      - '--collector.filesystem'
      - '--collector.diskstats'
      - '--collector.cpu'
      - '--collector.cpufreq'
      - '--collector.meminfo'
      - '--collector.hwmon'
      - '--collector.uname'
      - '--collector.time'
      - '--collector.stat'
      - '--collector.filesystem.fs-types-include=(ext4)'
    pid: host
    user: root
    hostname: nugget_node
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring
    volumes:
      - '/:/host:ro'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
